# Generated by Django 4.1.5 on 2023-03-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
