# Generated by Django 4.1.5 on 2023-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
