# Generated by Django 4.1.5 on 2023-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todomodel_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='end_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
